language: go

go:
  - 1.0
  - 1.1
  - 1.2
  - 1.3
  - tip

# For Go < v1.2, test imports also need to be installed.
install:
  - go get github.com/stretchr/testify/assert
  - go get github.com/stretchr/testify/suite
